<div class="container-fluid">

<h1>Artwork Request Detail</h1><br/>

<div class="row-fluid">

<div class="span8">

        <div class="well">

        <?php

        $artRequestTypesString = "";

        foreach($this->artRequest->getArtRequestArtRequestTypes() as $type)
        {
        	if($artRequestTypesString != "") {
        		$artRequestTypesString = $artRequestTypesString . ", ";
        	}
        	$artRequestTypesString = $artRequestTypesString . $type->getArtRequestType()->getArtRequestTypeName();
        }

        $bannerLocationList = "";

        foreach($this->artRequest->getBannerArtRequests() as $currentBanner)
        {
            if($bannerLocationList != "") {
                $bannerLocationList = $bannerLocationList . ", ";
            }
            $bannerLocationList = $bannerLocationList . $currentBanner->getBannerLocation()->getBannerLocationName();
        }

        if ($bannerLocationList != "") {
            $bannerRow = $bannerRow . "<dt>Banner Locations</dt>";
            $bannerRow = $bannerRow . "<dd>";
            $bannerRow = $bannerRow . $bannerLocationList;
            $bannerRow = $bannerRow . "</dd>";
        }

        $flyerRow = "";

        $flyerObject = $this->artRequest->getFlyerArtRequests()->getFirst();

        if ($flyerObject) {
            $flyerFormatString = $flyerObject->getFlyerFormat()->getFlyerFormatType();
            $flyerSizeString = $flyerObject->getFlyerSize()->getFlyerSizeType();

            $flyerRow = $flyerRow . "<dt>Flyer Info</dt>";
            $flyerRow = $flyerRow . "<dd>";
            $flyerRow = $flyerRow . $flyerFormatString . " " . $flyerSizeString;
            $flyerRow = $flyerRow . "</dd>";
        }

        print '<a class="btn" href="' . $this->url('ArtRequest-manage') . '"><i class="icon-arrow-left"></i> All Requests</a>';

        	print '<dl class="dl-horizontal">';

        		print "<dt>Contact Name</dt>"
        		."<dd>"
        		.$this->artRequest->getArtRequestor()->getFirstName() . " " . $this->artRequest->getArtRequestor()->getLastName()
        		."</dd>"
        		."<dt>Contact Email</dt>"
        		."<dd>"
        		.$this->artRequest->getArtRequestor()->getEmailAddress()
        		."</dd>"
        		."<dt>Contact Phone</dt>"
        		."<dd>"
        		.$this->artRequest->getArtRequestor()->getPhoneNumber()
        		."</dd>"
        		."<br/>"
        		."<dt>Due Date</dt>"
        		."<dd>"
        		.$this->artRequest->getDueDate()
        		."</dd>"
        		."<br/>"
        		."<dt>Artwork Types</dt>"
        		."<dd>"
        		.$artRequestTypesString
        		."</dd>"
        		."<dt>Artwork Description</dt>"
        		."<dd>"
        		.$this->artRequest->getArtRequestDescription()
        		."</dd>"
                . $bannerRow
                . $flyerRow
        		."<br/>"
        		."<dt>Event Title</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventTitle()
        		."</dd>"
        		."<dt>Event Location</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventLocation()
        		."</dd>"
        		."<dt>Event Sponsor</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventSponsorName()
        		."</dd>"
        		."<dt>Event Start Date &amp; Time</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventStartDate() . " " . $this->artRequest->getEvent()->getEventStartTime()
        		."</dd>"
        		."<dt>Event End Date &amp; Time</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventEndDate() . " " . $this->artRequest->getEvent()->getEventEndTime()
        		."</dd>"
        		."<dt>Event Description</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventDescription()
        		."</dd>"
        		."<br/>"
        		."<dt>Event Member Price</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventPricingMember()
        		."</dd>"
        		."<dt>Event Student Price</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventPricingStudent()
        		."</dd>"
        		."<dt>Event Staff Price</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventPricingStaff()
        		."</dd>"
        		."<dt>Event Public Price</dt>"
        		."<dd>"
        		.$this->artRequest->getEvent()->getEventPricingPublic()
        		."</dd>"
        		."<br/>";

        		print "<dt>Attached Files</dt>";
        		print "<dd>";

                $filesAttached = false;
                $attachmentNames = "";
        		
                foreach($this->artRequest->getArtRequestAttachments() as $attachment) 
                {
                    $filesAttached = true;
                    $attachmentNames = $attachmentNames . $attachment->getFileName() . "<br/>";
                }

                if(!$filesAttached) {
                    $attachmentNames = "(None)";
                }

                print($attachmentNames);

        		print "</dd>";

        	print "</dl>";

            if($filesAttached) {
                print '<a href="'
                . $this->url('ArtRequest-manage', array('action' => 'download-attachments', 'id' => $this->artRequest->getArtRequestId()))
                . '" class="btn btn-primary" target="_blank"><i class="icon-download"></i> Download Attachments</a>';
            }

        	?>

        </div>

</div>

<div class="span4">

    <div class="well">
        
        <?php

        $isStarted = "";
        $isCompleted = "";
        $isArchived = "";

        if($this->artRequest->getIsStarted() == 1) {$isStarted = "checked";}
        if($this->artRequest->getIsCompleted() == 1) {$isCompleted = "checked";}
        if($this->artRequest->getIsArchived() == 1) {$isArchived = "checked";}

            print '<form action="'
                . $this->url('ArtRequest-manage', array('action' => 'update-status', 'id' => $this->artRequest->getArtRequestId()))
                . '" method="post">'
                . '<div class="control-group">'
                . '<div class="controls">'
                . '<div class="checkbox-group-container">'
                . '<label class="checkbox inline"><input type="checkbox" class="checkbox-group" name="is_started" '
                . $isStarted
                . '>Started</label>'
                . '<label class="checkbox inline"><input type="checkbox" class="checkbox-group" name="is_completed" '
                . $isCompleted
                . '>Completed</label>'
                . '<label class="checkbox inline"><input type="checkbox" class="checkbox-group" name="is_archived" '
                . $isArchived
                . '>Archived</label>'
                . '</div>'
                . '</div>'
                . '</div>'
                . 'Artist(s)'
                . '<br/>'
                . '<select name="artist_ids[]" multiple="multiple">';

            $assignedArtistsIds = array();

            foreach ($this->artRequest->getArtRequestAssignments() as $assignedArtist) {
                array_push($assignedArtistsIds, $assignedArtist->getArtistId());
            }

            foreach($this->artists as $artist) {
                $selectedString = '';

                if(in_array($artist->getArtistId(), $assignedArtistsIds)) {
                    $selectedString = ' selected="selected"';
                }
                print '<option value="'
                . $artist->getArtistId()
                . '"'
                . $selectedString
                .'>';
                print $artist->getArtistFirstName() . " " . $artist->getArtistLastName() ." (" . $artist->getArtistDceName() . ")";
                print '</option>';
            }

            print '</select>'
                . '<br/>'
                . '<button class="btn btn-primary" type="submit">Save</button>'
                . '</form>';

        ?>

    </div>

</div>

</div>

</div>