<?php
// Generated by ZF2's ./bin/classmap_generator.php

return array(
    'FreezeFest\Controller\IndexController'               	     => __DIR__ . '/src/FreezeFest/Controller/IndexController.php',
    'FreezeFest\Email\FreezeFestEventRequestEmail'                  => __DIR__ . '/src/FreezeFest/Email/FreezeFestEventRequestEmail.php',
    'FreezeFest\Service\FreezeFestEventRequestService'              => __DIR__ . '/src/FreezeFest/Service/FreezeFestEventRequestService.php',
    'FreezeFest\Service\Entity\FreezeFestEventRequestServiceEntity' => __DIR__ . '/src/FreezeFest/Service/FreezeFestEventRequestServiceEntity.php',
);