INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (1,'Banner Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (2,'LCD Screen Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (3,'Table Tent Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (4,'Postcard Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (5,'Flyer Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (6,'Logo Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (7,'Ticket Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (8,'Window Request');
INSERT INTO art_request_type (art_request_type_id,art_request_type_name) VALUES (9,'Other Request');
INSERT INTO banner_location (banner_location_id,banner_location_name) VALUES (1,'Grace Watson Lobby');
INSERT INTO banner_location (banner_location_id,banner_location_name) VALUES (2,'Student Development Center');
INSERT INTO banner_location (banner_location_id,banner_location_name) VALUES (3,'SAU Lobby');
INSERT INTO event_price_type (event_price_type_id,event_price_type_name) VALUES (1,'Member');
INSERT INTO event_price_type (event_price_type_id,event_price_type_name) VALUES (2,'Staff');
INSERT INTO event_price_type (event_price_type_id,event_price_type_name) VALUES (3,'Student');
INSERT INTO event_price_type (event_price_type_id,event_price_type_name) VALUES (4,'Public');
INSERT INTO flyer_format (flyer_format_id,flyer_format_type) VALUES (1,'Color');
INSERT INTO flyer_format (flyer_format_id,flyer_format_type) VALUES (2,'Black & White');
INSERT INTO flyer_size (flyer_size_id,flyer_size_type) VALUES (1,'8.5" x 11"');
INSERT INTO flyer_size (flyer_size_id,flyer_size_type) VALUES (2,'11" x 17"');
