<?php
// This file generated by Propel 1.6.5-dev convert-conf target
// from XML runtime conf file C:\Art_Request\module\ArtRequest\tests\Model\configs\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'orm' => 
    array (
      'adapter' => 'sqlite',
      'connection' => 
      array (
        'dsn' => 'sqlite::memory:',
        'classname' => 'DebugPDO',
        'options' => 
        array (
          'ATTR_PERSISTENT' => 
          array (
            'value' => false,
          ),
        ),
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
          'queries' => 
          array (
            'query' => 'PRAGMA foreign_keys = ON;',
          ),
        ),
      ),
    ),
    'default' => 'orm',
  ),
  'generator_version' => '1.6.5-dev',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-orm-conf.php');
return $conf;