<?php echo $this->doctype();?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Contract Request - Center for Campus Life');?>
        <?php
        echo $this->headMeta()->appendName('viewport',
                'width=device-width, initial-scale=1.0')
        ?>
        <?php
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
        ?>
    </head>
    <body>
		<div id="metanav">
					<!-- <ul> -->
							<li id="metarithome"><a href="http://www.rit.edu/" title="RIT Home"><span id="metarithometext">RIT Home</span><span id="metaritlogo"></span></a></li>
							<!--<li id="metaritdirectories"><a href="http://www.rit.edu/directories/">Directories</a></li>
							<li id="metaritsearch"><a href="http://www.rit.edu/search/">Search RIT</a>
		                        <div id="metaritsearchdiv">
		                            <form id="metasearchform" method="get" action="http://www.rit.edu/search/">
		                                <div>
		                                    <input id="metaritsearchbox" class="faded" name="q" type="text" value="Search RIT" maxlength="250" alt="Search box" onfocus="focusSearch(this)" 
		                                        onblur="blurSearch(this)" />
		                                    <button title="Submit Search">Search</button>
		                                </div>
		                            </form>
		                        </div>
							</li>
						</ul>
						<script type="text/javascript">
						function focusSearch(formfield){ if (formfield.defaultValue==formfield.value) formfield.value = ""; formfield.className = ""; }
						function blurSearch(formfield){ if (formfield.value==""){ formfield.value = formfield.defaultValue; formfield.className = "faded";} }
						</script> -->
		</div>
		<header>
			<!-- <div>
				<a href="https://campuslife.rit.edu">
					<div class="logo"></div>
				</a>
			</div> -->
		</header>
        <!-- Header Here -->
        <div class="container">
            <?php echo $this->content;?>
        </div> <!-- /container -->
        <!-- Footer Here -->
        <?php echo $this->inlineScript()?>
    </body>
</html>