<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'API\Module'                                                => __DIR__ . '/Module.php',
    'API\Controller\LdapController'                             => __DIR__ . '/src/API/Controller/LdapController.php',
    'API\Controller\OrganizationController'                     => __DIR__ . '/src/API/Controller/OrganizationController.php',
    'API\Controller\UserController'                             => __DIR__ . '/src/API/Controller/UserController.php',
    'API\ControllerFactory\UserControllerFactory'               => __DIR__ . '/src/API/ControllerFactory/UserControllerFactory.php',
    'API\Model\OrganizationModel'                               => __DIR__ . '/src/API/Model/OrganizationModel.php',
    'API\Model\UserModel'                                       => __DIR__ . '/src/API/Model/UserModel.php',
    'API\Service\LDAP\Entity\LDAPServiceEntity'                 => __DIR__ . '/src/API/Service/LDAP/Entity/LDAPServiceEntity.php',
    'API\Service\LDAP\iLDAPService'                             => __DIR__ . '/src/API/Service/LDAP/iLDAPService.php',
    'API\Service\LDAP\LDAPService'                              => __DIR__ . '/src/API/Service/LDAP/LDAPService.php',
    'API\Service\Organization\Entity\OrganizationServiceEntity' => __DIR__ . '/src/API/Service/Organization/Entity/OrganizationServiceEntity.php',
    'API\Service\Organization\iOrganizationService'             => __DIR__ . '/src/API/Service/Organization/iOrganizationService.php',
    'API\Service\Organization\OrganizationService'              => __DIR__ . '/src/API/Service/Organization/OrganizationService.php',
    'API\Service\User\Entity\UserServiceEntity'                 => __DIR__ . '/src/API/Service/User/Entity/UserServiceEntity.php',
    'API\Service\User\iUserService'                             => __DIR__ . '/src/API/Service/User/iUserService.php',
    'API\Service\User\UserService'                              => __DIR__ . '/src/API/Service/User/UserService.php',
);