
    <div class="page-header">
        <h1>
            Commuter SpiRIT Week Registration Confirmation <br/> 
            <small>March 11th - March 15th, 2013</small>
        </h1>
    </div>

<div class="row-fluid">
    <div class="well">
        <h3>Thank you for registering to participate in RIT's first-ever Commuter SpiRIT Week!  This serves as confirmation that you are registered to be able to participate in activities, win free giveaways, free food, and receive coupons and incentives specifically for commuter students throughout the week of March 11-15, 2013.</h3>
	</div>
</div>

<div class="row-fluid">

	<div class="well">
		<h3>Things to Keep in Mind:</h3>
		
		<ol>
			<li>Please visit rit.edu/ace for a full calendar of events, or ACE at RIT on Facebook</li>
			<li> After you received this confirmation email you can come to the ACE Office, in the Campus Center A650 to receive your wristband anytime the week prior to the event.  You can also collect your wristband on Monday March 11th at the Commuter Fair in the Fireside Lounge in the Campus Center.  If alternative arrangements need to be made please contact <a href="mailto:cjmccl@rit.edu">Clay Monson</a></li>
			<li>By entering your information into the registration system you are eligible for items specifically for commuter students and will be kept aware and updated of events happening on campus for commuter and off campus populations</li>
			<li>You MUST have your wristband represented to participate in the events during Commuter SpiRIT Week - you don't need to be wearing it, but you need to show you have it.</li>
		</ol>
		
		<p>
			Please contact <a href="mailto:cjmccl@rit.edu">Clay Monson</a> with any questions you might have!  Thank you, and see you there!
		</p>
    </div>
	</div>
</div>