<div class="container-fluid">

<div class="row-fluid">

<div class="span8 offset2">

    <h1>Artwork Request</h1><br/>

    <form id="art_request_form" name="art_request_form" method="POST" enctype="multipart/form-data" action="/app/art-request/create">

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>Tell Us About Yourself</h3>
                </div>

                <div class="row-fluid">

                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label" for="phone_number">Phone Number:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-phone"></i></span>
                                    <input type="text" id="phone_number" name="phone_number" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!--Row End-->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>When Do You Need It By?</h3>

                    <p>
                        Your request must be submitted <b>at least 2 weeks before your art is needed</b>. If you need it in less time please contact
                        <a href="mailto:radccl@rit.edu?subject=Art Request">Rebecca Delaney</a> for approval.
                    </p>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <div class="control-group">
                            <label class="control-label" for="request_due_date">Request Due Date:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-calendar"></i></span>
                                    <input type="text" id="request_due_date" name="request_due_date" />
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div> <!-- Well End -->

        </div> <!--Row End-->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>What Do You Need Made?</h3>
                </div>

                <div class="row-fluid">

                    <div class="control-group indent-checkbox-group">
                        <div class="controls span3">
                            <div class="checkbox-group-container">
                                <?php
                                foreach($this->artRequestTypeData as $artRequestType)
                                {
                                    print '<label class="checkbox">';
                                    print '<input type="checkbox" class="checkbox-group" name="art_request_type[]" value="' . $artRequestType->getArtRequestTypeId() . '" id="' . str_replace(" ",
                                                    "_",
                                                    $artRequestType->getArtRequestTypeName()) . '">' . $artRequestType->getArtRequestTypeName();
                                    print '</label>';
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls span7 offset1">
                            <div class="control-group">
                                <label class="control-label" for="request_description">Description:</label>
                                <div class="controls">
                                    <textarea rows="5" cols="5" id="request_description" name="request_description" class="span12"></textarea>
                                </div>
                            </div>                        
                        </div>
                    </div>

                </div>

            </div> <!-- Well End -->

        </div> <!-- Row End -->

        <div class="row-fluid" id="flyer-request-container">

            <div class="well">

                <div class="row-fluid">
                    <h3>Flyer Request</h3>
                </div>

                <div class="row-fluid">
                    <div class="control-group">
                        <label class="control-label" for="flyer_format_id">Flyer Format:</label>
                        <div class="controls">
                            <select id="flyer_format_id" name="flyer_format_id" class="span3">
                            <option value="">Select a Flyer Format</option>
                            <?php
                            foreach($this->flyerFormatData as $flyerFormatType)
                            {
                                print '<option value="' . $flyerFormatType->getFlyerFormatId() . '">' . $flyerFormatType->getFlyerFormatType() . '</option>';
                            }
                            ?>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="control-group">
                        <label class="control-label" for="flyer_size_id">Flyer Size:</label>
                        <div class="controls">
                            <select id="flyer_size_id" name="flyer_size_id" class="span3">
                            <option value="">Select a Flyer Size</option>
                            <?php
                            foreach($this->flyerSizeData as $flyerSizeType)
                            {
                                print '<option value="' . $flyerSizeType->getFlyerSizeId() . '">' . $flyerSizeType->getFlyerSizeType() . '</option>';
                            }
                            ?>
                            </select>
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <div class="row-fluid" id="banner-request-container">

            <div class="well">

                <div class="row-fluid">
                    <h3>Banner Request</h3>
                </div>

                <div class="row-fluid">
                    <p>Select the locations where you need banners. The banner size is 3' x 6'.</p>
                    <div class="controls indent-checkbox-group">
                        <?php
                        foreach($this->bannerLocationData as $bannerLocationType)
                        {
                            print '<label class="checkbox">';
                            print '<input type="checkbox" name ="banner_location_id[]" value="' . $bannerLocationType->getBannerLocationId() . '" id="' . $bannerLocationType->getBannerLocationId() . '">' . $bannerLocationType->getBannerLocationName();
                            print '</label>';
                        }
                        ?>
                    </div>
                </div>

            </div>

        </div>

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>
                        Event Information
                    </h3>
                </div>
                <div class="row-fluid">
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="event_title">Title:</label>
                            <div class="controls">
                                <input type="text" id="event_title" name="event_title" style="width: 90%;" />
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="event_location">Location:</label>
                            <div class="controls">
                                <input type="text" id="event_location" name="event_location" style="width: 90%;"/>
                            </div>  
                        </div>
                    </div>
                    <div class="span4">
                        <div class="control-group">
                            <label class="control-label" for="event_sponsor_name">Sponsor:</label>
                            <div class="controls controls-row">
                                <input type="text" id="event_sponsor_name" name="event_sponsor_name" style="width: 90%;"/>
                            </div> 
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_start_date">Start Date:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-calendar"></i></span>
                                    <input id="event_start_date" name="event_start_date" type="text" class="span7" />                                
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="event_end_date">End Date:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-calendar"></i></span>
                                    <input id="event_end_date" name="event_end_date" type="text" class="span7" />
                                </div>
                            </div>
                        </div>                        
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_start_time">Start Time:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-time"></i></span>
                                    <input id="event_start_time" name="event_start_time" type="text" class="span7" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="span3 offset1">
                        <div class="control-group">
                            <label class="control-label" for="event_end_time">End Time:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on"><i class="icon-time"></i></span>
                                    <input id="event_end_time" name="event_end_time" type="text" class="span7" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <div class="control-group">
                            <label class="control-label" for="event_description">Description:</label>
                            <div class="controls">
                                <textarea rows="5" cols="5" id="event_description" name="event_description" class="span9"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- Well End -->

        </div> <!-- Row End -->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <h3>
                        Event Pricing
                    </h3>
                </div>

                <div class="row-fluid">

                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_pricing_member">Member:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on">$</span>
                                    <input type="text" id="event_pricing_member" name="event_pricing_member" class="span7" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_pricing_student">Student:</label> 
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on">$</span>
                                    <input type="text" id="event_pricing_student" name="event_pricing_student"  class="span7" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_pricing_staff">Staff:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on">$</span>
                                    <input type="text" id="event_pricing_staff" name="event_pricing_staff" class="span7" />
                                </div> 
                            </div>
                        </div>
                    </div>

                    <div class="span3">
                        <div class="control-group">
                            <label class="control-label" for="event_pricing_public">Public:</label>
                            <div class="controls">
                                <div class="input-prepend">
                                    <span class="add-on">$</span>
                                    <input type="text" id="event_pricing_public" name="event_pricing_public" class="span7" />
                                </div>
                            </div>
                        </div>
                    </div>


                </div>

            </div> <!-- End Well -->

        </div> <!-- End Row -->

        <div class="row-fluid">

            <div class="well">

                <div class="row-fluid">
                    <div class="pull-left"> 
                        <h3>Attach Any Relevant Files</h3>
                    </div>
                    <div class="pull-right">
                        <input type="button" value="Remove Last" id="remove_file_attachment" name="remove_file_attachment" class="btn btn-danger"/>
                        <input type="button" value="Add Attachment" id="add_file_attachment" name="add_file_attachment" class="btn btn-primary"/>
                    </div>
                </div>
                
                <div class="row-fluid">
                    Maximum Total Upload Size: 50 MB
                </div>

                <div class="row-fluid file-attachment-row">
                    <div class="control-group">
                        <div class="controls controls-row">
                        <div class="fileupload fileupload-new" data-provides="fileupload">
                    <div class="input-append">
                      <div class="uneditable-input span3">
                          <i class="icon-file fileupload-exists"></i>
                          <span class="fileupload-preview"></span>
                      </div>
                        <span class="btn btn-file">
                            <span class="fileupload-new">Select</span>
                            <span class="fileupload-exists">Change</span>
                            <input type="file" name="attachment[]" id="attachment"/>
                        </span>
                        <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Clear</a>
                    </div>
                  </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="form-actions">                
            <button type="submit" class="btn btn-primary btn-large">Submit</button>
        </div>
        
        <input type="hidden" name="has_flyer_request" id="has_flyer_request" value="false" />
        <input type="hidden" name="has_banner_request" id="has_banner_request" value="false" />

    </form>

</div>

</div>

</div>