<div class="container-fluid">

<div class="row-fluid">

<div class="span8 offset2">

    <h1>Artwork Request</h1><br/>

    <div class="row-fluid">

        <div class="well">

            <div class="row-fluid">
                
                <h3>Success!</h3>

            	You have successfully submitted your artwork request. You should receive a confirmation email shortly.

            	<br/>
            	<br/>

            </div>

        </div>

    </div>

</div>

</div>

</div>